#!/usr/bin/env bash

whoami
pwd
ls -lsa
composer install
npm install
npm run production
php artisan storage:link
php artisan migrate --force
php artisan config:cache
php artisan route:cache
php artisan view:cache
