version: '3.9'
services:
  laravel.test:
    ports:
      - '${FORWARD_PHP_PORT:-9000}:9000'
  nginx:
    ports:
      - '${FORWARD_NGINX_PORT:-80}:80'
  mysql:
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
  redis:
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
  meilisearch:
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_SMTP_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
